# Generated by Django 3.2.18 on 2023-04-27 11:23

import tags.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[tags.validators.hex_color_validate]),
        ),
    ]
